server:
  port: 8181

spring:
  config:
    import: "optional:configserver:http://localhost:8888"
  application:
    name: movie-web

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/


