spring:
  application:
    name: movies

  config:
    import: "optional:configserver:http://localhost:8888"

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: false