server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CynicDog/Spring-Cloud-Data-Flow-Demo-Config
          username: eunsang_lee
          password: # your git personal access token
          default-label: main